# to get started:
# pip install mkdocs
# pip install mkdocs-mermaid2-plugin

site_name: Mealplanner (Good Meal Plan) Guide

nav:
  - Home: index.md
  - Front End: 
    - Login: login.md
    - Logout: logout.md
    - Create a Mealplan: create-a-mealplan.md
    - Create a Meal Template: create-a-meal-template.md
    - Create a Mealplan from a Template: create-mealplan-from-template.md
    - Delete a Mealplan: delete-a-mealplan.md
    - Finding Meals: mealplanner-ui-meals.md
    - View Shopping List: view-shopping-list.md
  - Admin UI: 
    - Nutrition: nutrition1.md
    - Meals: admin-ui-meals.md

theme:
  name: readthedocs
  nav_style: dark
  highlightjs: true

plugins:
  - search
  - mermaid2:
      javascript: https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs


